CI: fix Coveralls job
grcov 0.10.7 can't be installed because uuid requires a newer Rust
version:

    error: failed to compile `grcov v0.10.7`, intermediate artifacts can be found at `/tmp/cargo-installWfPKi5`.
    To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

    Caused by:
      rustc 1.88.0 is not supported by the following package:
        uuid@1.27.0 requires rustc 1.89.0