Add missing header and fix build on FreeBSD
In file included from src/queuemanager.cpp:1:
include/queuemanager.h:22:9: error: unknown type name 'time_t'
                const time_t pubDate,
                      ^

Signed-off-by: Tobias Kortkamp <tobik@FreeBSD.org>