Avoid implicit switch fallthrough in tagparser
Newer gcc versions (>= 7) introduce a warning in -Wextra for case's
potentially lacking "break" in switch statements:

src/tagsouppullparser.cpp: In member function ‘newsbeuter::tagsouppullparser::event newsbeuter::tagsouppullparser::next()’:
src/tagsouppullparser.cpp:73:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if (c != '<') {
   ^~
src/tagsouppullparser.cpp:77:2: note: here
  case event::TEXT:
  ^~~~

The documentation gives many options for using magic comments to silence
the warning as well as mentioning various attributes applying to
different standards, but instead of silencing the warning in one of
these ways the code is changed to not use a fallthrough instead for
simplicity as there isn't a real gain from the fallthrough here.