Rename next -> extract_next
Clippy complained about `next()` being used on something which is not an
iterator:
```
error: method `next` can be confused for the standard trait method `std::iter::Iterator::next`
  --> rust/libnewsboat/src/tagsouppullparser.rs:33:5
   |
33 | /     pub fn next(self: &mut TagSoupPullParser) -> &Event {
34 | |         self.attributes.clear();
35 | |         self.text.clear();
36 | |
...  |
56 | |         self.get_event_type()
57 | |     }
   | |_____^
   |
   = note: `-D clippy::should-implement-trait` implied by `-D warnings`
   = help: consider implementing the trait `std::iter::Iterator` or choosing a less ambiguous method name
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#should_implement_trait
```