include/listwidgetbackend.h: add missing <cstdint> include
Upcoming `gcc-13` made `<string>` leaner and does not include `<cstdint>`
implicitly anymore. As a result build fails without the change as:

    include/listwidgetbackend.h:16:37: error: 'std::uint32_t' has not been declared
       16 |         void stfl_replace_list(std::uint32_t number_of_lines, std::string stfl);
          |                                     ^~~~~~~~